In [1]:
!pip install pyjarowinkler
!pip install editdistance
!pip install Unidecode
!pip install affine

You should consider upgrading via the 'c:\users\bookw\anaconda3\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\bookw\anaconda3\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\bookw\anaconda3\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\bookw\anaconda3\python.exe -m pip install --upgrade pip' command.


In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from difflib import SequenceMatcher
import re
from pyjarowinkler.distance import get_jaro_distance
import editdistance
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop=set(stopwords.words('english'))
import string
#from unidecode import unidecode

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bookw\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
unified_add_df = pd.read_csv('addresses.csv')

In [3]:
unified_add_df.reset_index(drop=True, inplace=True)

In [4]:
unified_add_df

Organization name  \
0                   NEELAM ENTERPRISES   
1                   NEELAM ENTERPRISES   
2       Formosa Industries Corporation   
3       Formosa Industries Corporation   
4    Formosa Taffeta Dong Nai Co., Ltd   
..                                 ...   
160           Nahar Spinning Mills Ltd   
161           Nahar Spinning Mills Ltd   
162           Nahar Spinning Mills Ltd   
163           Nahar Spinning Mills Ltd   
164   Nahar Spinning Mills Limited-373   

                                         Address value               Source  \
0                           E-7/4 KRISHNA NAGAR, DELHI                  OAR   
1                                  E-7/4 KRISHNA NAGAR  Better Cotton Excel   
2    Nhon Trach 3 Industrial Zone,Nhon Trach Dist, ...                  OAR   
3      Nhon Trach 3 I.Z, Nhon Trach, Phu Hoi, Dong Nai                  OAR   
4                        Vietnam, Dong Nai, Nhon Trach         SLCP_GATEWAY   
..                                                 ...                  ...   
160  427, Industrial Area-A, Ludhiana-141 003 (Indi...                  OAR   
161        Plot# 427,, 141003, Ludhiana, Punjab, India                  OAR   
162  K/A : Mr. Anil Anand, Nahar Spinning Mills Ltd...                  OAR   
163  371-37 375-378 381 425 427 RK Road Industrial ...                  OAR   
164       373, Industrial Area A Ludhiana Punjab India                  OAR   

    Unnamed: 3  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
..         ...  
160        NaN  
161        NaN  
162        NaN  
163        NaN  
164        NaN  

[165 rows x 4 columns]

##  Jaro and Jaro-Winkler similarity

In [5]:
from math import floor, ceil

In [6]:
# Function to calculate the
# Jaro Similarity of two s
def jaro_distance(s1, s2):
     
    # If the s are equal
    if (s1 == s2):
        return 1.0
 
    # Length of two s
    len1 = len(s1)
    len2 = len(s2)
 
    # Maximum distance upto which matching
    # is allowed
    max_dist = floor(max(len1, len2) / 2) - 1
 
    # Count of matches
    match = 0
 
    # Hash for matches
    hash_s1 = [0] * len(s1)
    hash_s2 = [0] * len(s2)
 
    # Traverse through the first
    for i in range(len1):
 
        # Check if there is any matches
        for j in range(max(0, i - max_dist),
                       min(len2, i + max_dist + 1)):
             
            # If there is a match
            if (s1[i] == s2[j] and hash_s2[j] == 0):
                hash_s1[i] = 1
                hash_s2[j] = 1
                match += 1
                break
 
    # If there is no match
    if (match == 0):
        return 0.0
 
    # Number of transpositions
    t = 0
    point = 0
 
    # Count number of occurrences
    # where two characters match but
    # there is a third matched character
    # in between the indices
    for i in range(len1):
        if (hash_s1[i]):
 
            # Find the next matched character
            # in second
            while (hash_s2[point] == 0):
                point += 1
 
            if (s1[i] != s2[point]):
                point += 1
                t += 1
    t = t//2
 
    # Return the Jaro Similarity
    return (match/ len1 + match / len2 +
            (match - t + 1) / match)/ 3.0

In [7]:
# Driver code
s1 = "E-7/4 KRISHNA NAGAR, DELHI"
s2 = "E-7/4 KRISHNA NAGAR"
s3 = "Nhon Trach 3 I.Z, Nhon Trach, Phu Hoi, Dong Nai"
s4 = "Nhon Trach 3 Industrial Park, Hiep Phuoc Ward, Nhon Trach District, Dong Nai Province, Vietnam Bien Hoa Dong Nai Province"
s5 = "Nhon Trach 3 Industrial Zone,Nhon Trach Dist, (untracebale in geolocation)"
s6 = "Vietnam, Dong Nai, Nhon Trach"

In [8]:
# Prjaro Similarity of two s
print(round(jaro_distance(s1, s2),6))

0.769906


In [9]:
print(round(jaro_distance(s3, s4),6))

0.635708


## Levenshtein distance

In [10]:
!pip install python-Levenshtein

In [11]:
from difflib import ndiff
from Levenshtein import distance as levenshtein_distance

In [12]:
def calculate_levenshtein_distance(str_1, str_2):
    """
        The Levenshtein distance is a string metric for measuring the difference between two sequences.
        It is calculated as the minimum number of single-character edits necessary to transform one string into another
    """
    distance = 0
    buffer_removed = buffer_added = 0
    for x in ndiff(str_1, str_2):
        code = x[0]
        # Code ? is ignored as it does not translate to any modification
        if code == ' ':
            distance += max(buffer_removed, buffer_added)
            buffer_removed = buffer_added = 0
        elif code == '-':
            buffer_removed += 1
        elif code == '+':
            buffer_added += 1
    distance += max(buffer_removed, buffer_added)
    return distance


In [13]:
print(round(calculate_levenshtein_distance(s1, s2),6))

7


In [14]:
print(round(calculate_levenshtein_distance(s3, s4),6))

89


## Edit distance

In [ ]:
# A Naive recursive Python program to fin minimum number
# operations to convert str1 to str2
# taking more time to compute

def editDistance(str1, str2, m, n):
 
    # If first string is empty, the only option is to
    # insert all characters of second string into first
    if m == 0:
        return n
 
    # If second string is empty, the only option is to
    # remove all characters of first string
    if n == 0:
        return m
 
    # If last characters of two strings are same, nothing
    # much to do. Ignore last characters and get count for
    # remaining strings.
    if str1[m-1] == str2[n-1]:
        return editDistance(str1, str2, m-1, n-1)
 
    # If last characters are not same, consider all three
    # operations on last character of first string, recursively
    # compute minimum cost for all three operations and take
    # minimum of three values.
    return 1 + min(editDistance(str1, str2, m, n-1),    # Insert
                   editDistance(str1, str2, m-1, n),    # Remove
                   editDistance(str1, str2, m-1, n-1)    # Replace
                   )

In [ ]:
print(editDistance(s1, s2, len(s1), len(s2)))

In [ ]:
print(editDistance(s3, s4, len(s3), len(s4)))

## Using these algorithms from the jellyfish library

In [15]:
import jellyfish

In [16]:
jellyfish.levenshtein_distance(s3, s4)

80

In [17]:
jellyfish.jaro_distance(s3, s4)

0.6653381005411952

In [18]:
jellyfish.damerau_levenshtein_distance(s3, s4)

80

In [19]:
jellyfish.damerau_levenshtein_distance(s3, s5)

43

In [20]:
jellyfish.jaro_winkler_similarity(s3, s4)

0.6653381005411952

In [21]:
jellyfish.hamming_distance(s3, s4)

104

In [22]:
jellyfish.match_rating_comparison(s3,s4)

True

In [23]:
jellyfish.jaro_distance(s3, s5)

0.7031071029514205

In [24]:
def jaccard(str1, str2): 
    a = set(str1.lower().split()) 
    b = set(str2.lower().split())
    c = a.intersection(b)
    return float(len(c)) / (len(a) + len(b) - len(c))

In [25]:
jaccard(s3, s4)

0.25

In [26]:
sample = "No. 1, Penghu Road,, Hi-Tech Industry Development Zone,, (blank)"

In [27]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\([^)]*\)', '', text)
    text = re.sub('\[.*?\]', '', text)
    text = ' '.join([word for word in text.split(' ') if word not in stop])
    text = text.encode('ascii', 'ignore').decode()
    text = re.sub(r'https*\S+', ' ', text)
    text = re.sub(r'@\S+', ' ', text)
    text = re.sub(r'#\S+', ' ', text)
    text = re.sub(r'\'\w+', '', text)
    text = re.sub('no.', 'number', text)    
    text = re.sub('ltd.' or 'ltd', 'limited', text)
    text = re.sub('co.', 'cooperation', text)
    text = re.sub('pvt.' or 'pvt', 'private', text)
    #text = re.sub('(?<=\w)-(?=\w)', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = re.sub(r'\s{2,}', ' ', text)
    text = re.sub(r"^\s+|\s+$", "", text) 
    return text

In [28]:
t = clean_text(sample)
t

'number 1 penghu road hi tech industry development zone'

In [29]:
jellyfish.jaro_distance(clean_text(s3), clean_text(s4))

0.6885747757840782

In [30]:
!pip install py-stringmatching

In [31]:
from affine import Affine
import py_stringmatching
aff = py_stringmatching.similarity_measure.affine.Affine(gap_start=1, gap_continuation=0.5)
aff.get_raw_score(s3, s5)

14.5

In [32]:
aff.get_raw_score(clean_text(s3), clean_text(s5))

16.5

In [33]:
!pip install -U strsimpy

In [34]:
from strsimpy.levenshtein import Levenshtein
from strsimpy.normalized_levenshtein import NormalizedLevenshtein
from strsimpy.weighted_levenshtein import WeightedLevenshtein

levenshtein = Levenshtein()
normalized_levenshtein = NormalizedLevenshtein()

In [35]:
print(levenshtein.distance(s3, s4))

80


In [36]:
print(normalized_levenshtein.distance(s3, s4))

0.6611570247933884


In [37]:
print(normalized_levenshtein.distance(clean_text(s3), clean_text(s4)))

0.6581196581196581


In [38]:
def insertion_cost(char):
    return 1.0

def deletion_cost(char):
    return 1.0

def substitution_cost(char_a, char_b):
    if char_a == 't' and char_b == 'r':
        return 0.5
    return 1.0

weighted_levenshtein = WeightedLevenshtein(
    substitution_cost_fn=substitution_cost,
    insertion_cost_fn=insertion_cost,
    deletion_cost_fn=deletion_cost)

In [39]:
print(weighted_levenshtein.distance(s3, s4))

80.0


In [40]:
from strsimpy.longest_common_subsequence import LongestCommonSubsequence
lcs = LongestCommonSubsequence()

In [41]:
print(lcs.distance(s3, s4))

86


In [42]:
from strsimpy.metric_lcs import MetricLCS
metric_lcs = MetricLCS()
#The distance is computed as 1 - |LCS(s1, s2)| / max(|s1|, |s2|)

In [43]:
print(metric_lcs.distance(s3, s4))

0.6611570247933884


In [44]:
from strsimpy.cosine import Cosine
cosine = Cosine(2)

In [45]:
p0 = cosine.get_profile(s3)
p1 = cosine.get_profile(s4)
print(cosine.similarity_profiles(p0, p1))

0.6853155776839848


In [46]:
from strsimpy.ngram import NGram
twogram = NGram(2)
fourgram = NGram(4)

In [47]:
print(twogram.distance(s3, s4))

0.6074380165289256


In [48]:
print(fourgram.distance(s3, s4))

0.628099173553719


In [49]:
!pip install textdistance
!pip install "textdistance[extras]"
!pip install "textdistance[benchmark]"
!pip install "textdistance[Hamming]"

In [50]:
import textdistance

In [51]:
textdistance.hamming.normalized_similarity(s3, s4)

0.14049586776859502

In [52]:
textdistance.hamming.normalized_distance(s3, s4)

0.859504132231405

In [53]:
textdistance.jaccard(s3, s4)

0.36585365853658536

In [54]:
textdistance.cosine(s3, s4)

0.5967204197641142

In [55]:
textdistance.jaro_winkler(s3.split(), s4.split())

0.6333333333333333

In [56]:
textdistance.sorensen(s3.split(), s4.split())

0.4

In [57]:
!pip install googletrans
!pip install googletrans==3.1.0a0

In [58]:
import googletrans
from googletrans import Translator, constants
from pprint import pprint

# init the Google API translator
translator = Translator()

In [59]:
translation = translator.translate('Mitä sinä teet')
print(translation.text)

What are you doing


In [60]:
print(googletrans.LANGUAGES)

{'af': 'afrikaans', 'sq': 'albanian', 'am': 'amharic', 'ar': 'arabic', 'hy': 'armenian', 'az': 'azerbaijani', 'eu': 'basque', 'be': 'belarusian', 'bn': 'bengali', 'bs': 'bosnian', 'bg': 'bulgarian', 'ca': 'catalan', 'ceb': 'cebuano', 'ny': 'chichewa', 'zh-cn': 'chinese (simplified)', 'zh-tw': 'chinese (traditional)', 'co': 'corsican', 'hr': 'croatian', 'cs': 'czech', 'da': 'danish', 'nl': 'dutch', 'en': 'english', 'eo': 'esperanto', 'et': 'estonian', 'tl': 'filipino', 'fi': 'finnish', 'fr': 'french', 'fy': 'frisian', 'gl': 'galician', 'ka': 'georgian', 'de': 'german', 'el': 'greek', 'gu': 'gujarati', 'ht': 'haitian creole', 'ha': 'hausa', 'haw': 'hawaiian', 'iw': 'hebrew', 'he': 'hebrew', 'hi': 'hindi', 'hmn': 'hmong', 'hu': 'hungarian', 'is': 'icelandic', 'ig': 'igbo', 'id': 'indonesian', 'ga': 'irish', 'it': 'italian', 'ja': 'japanese', 'jw': 'javanese', 'kn': 'kannada', 'kk': 'kazakh', 'km': 'khmer', 'ko': 'korean', 'ku': 'kurdish (kurmanji)', 'ky': 'kyrgyz', 'lo': 'lao', 'la': 'lat

In [61]:
sample1 = 'Isil Tekstil San. ve Tic. Ltd. Sti'
sample2 = 'ISIL TEKSTIL'
sample3 = 'ISIL TEKSTIL SAN.VE TIC.LTD.STI - ISTANBUL'
sample4 = 'Işıl Kumaş San. Tic'

In [62]:
textdistance.jaro_winkler(sample3, sample4)

0.41217627401837925

In [63]:
textdistance.jaro_winkler(clean_text(sample3), clean_text(sample4))

0.5541343669250646

In [64]:
textdistance.jaro_winkler(sample1, sample4)

0.5226178190574475

In [65]:
textdistance.jaro_winkler(clean_text(sample1), clean_text(sample4))

0.5861111111111111

In [66]:
example = translator.translate(sample4)
if example.src != 'en':
    text = example.text
text

'Isil Fabric San. trade'

In [67]:
textdistance.jaro_winkler(sample3, text)

0.41630591630591635

In [68]:
textdistance.jaro_winkler(clean_text(sample3), clean_text(text))

0.6071659283868586

In [69]:
textdistance.jaro_winkler(sample1, text)

0.6492869875222816

In [70]:
aff.get_raw_score(sample1, text)

5.5

In [71]:
aff.get_raw_score(clean_text(sample1), clean_text(text))

6.0

In [72]:
aff.get_raw_score(sample1, sample4)

3.0

In [73]:
aff.get_raw_score(clean_text(sample1), clean_text(sample4))

1.5

In [74]:
sample5 = 'ÖZAY İPLİK TEKSTİL SANAYİ VE TİC. LTD. ŞTI'
sample6 = 'Ozay Nakis Tekstil Sanayi Ve Tic Ltd STI'

In [75]:
textdistance.jaro_winkler(sample5,sample6)

0.4686507936507936

In [76]:
textdistance.jaro_winkler(clean_text(sample5), clean_text(sample6))

0.7812881562881563

In [77]:
sam5 = translator.translate(sample5)
if sam5.src != 'en':
    sample5 = sam5.text
    print(sample5)

ÖZAY YARN TEXTILE INDUSTRY AND TRADE. LTD. STI


In [78]:
textdistance.jaro_winkler(sample5,sample6)

0.4781400966183575

In [79]:
textdistance.jaro_winkler(clean_text(sample5), clean_text(sample6))

0.7136971742935733

In [80]:
!pip install swalign

In [81]:
import swalign

match = 2
mismatch = -1
scoring = swalign.NucleotideScoringMatrix(match, mismatch)

sw = swalign.LocalAlignment(scoring)

In [82]:
alignment = sw.align(sample3,sample4)

In [83]:
def compare(m, n, match, n_match):
    if m == n:
        return match
    else:
        return n_match

def Smith_Waterman(seq1, seq2, mS, mmS, w1):
    path = {}
    S = np.zeros([len(seq1) + 1, len(seq2) + 1], int)

    for i in range(0, len(seq1) + 1):
        for j in range(0, len(seq2) + 1):
            if i == 0 or j == 0:
                path['[' + str(i) + ', ' + str(j) + ']'] = []
            else:
                if seq1[i - 1] == seq2[j - 1]:
                    s = mS
                else:
                    s = mmS
                L = S[i - 1, j - 1] + s
                P = S[i - 1, j] - w1
                Q = S[i, j - 1] - w1
                S[i, j] = max(L, P, Q, 0)
                path['[' + str(i) + ', ' + str(j) + ']'] = []
                if L == S[i, j]:
                    path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i - 1) + ', ' + str(j - 1) + ']')
                if P == S[i, j]:
                    path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i - 1) + ', ' + str(j) + ']')
                if Q == S[i, j]:
                    path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i) + ', ' + str(j - 1) + ']')

    print("S = ", S)
    end = np.argwhere(S == S.max())
    for i in end:
        key = str(list(i))
        value = path[key]
        result = [key]
        traceback(path, S, value, result, seq1, seq2)


def Smith_Waterman_aff(seq1, seq2, match, n_match, u, v):
    a = len(seq1)
    b = len(seq2)
    path = {}
    S = np.zeros((a + 1, b + 1))
    L = np.zeros((a + 1, b + 1))
    P = np.zeros((a + 1, b + 1))
    Q = np.zeros((a + 1, b + 1))
    seq1 = " " + seq1[:]
    seq2 = " " + seq2[:]
    for r in range(1, b + 1 if a > b else a + 1):
        for c in range(r, b + 1):
            L[r, c] = S[r - 1, c - 1] + compare(seq1[r], seq2[c], match, n_match)
            P[r, c] = max(np.add(S[0:r, c], -(np.arange(r, 0, -1) * u + v)))
            Q[r, c] = max(np.add(S[r, 0:c], -(np.arange(c, 0, -1) * u + v)))
            S[r, c] = max([0, L[r, c], P[r, c], Q[r, c]])
        for c in range(r + 1, a + 1):
            L[c, r] = S[c - 1, r - 1] + compare(seq1[c], seq2[r], match, n_match)
            P[c, r] = max(np.add(S[0:c, r], -(np.arange(c, 0, -1) * u + v)))
            Q[c, r] = max(np.add(S[c, 0:r], -(np.arange(r, 0, -1) * u + v)))
            S[c, r] = max([0, L[c, r], P[c, r], Q[c, r]])
        for i in range(0, len(seq1)):
            for j in range(0, len(seq2)):
                if i == 0 or j == 0:
                    path['[' + str(i) + ', ' + str(j) + ']'] = []
                else:
                    path['[' + str(i) + ', ' + str(j) + ']'] = []
                    if L[i,j] == S[i, j]:
                        path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i - 1) + ', ' + str(j - 1) + ']')
                    if P[i,j] == S[i, j]:
                        path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i - 1) + ', ' + str(j) + ']')
                    if Q[i,j] == S[i, j]:
                        path['[' + str(i) + ', ' + str(j) + ']'].append('[' + str(i) + ', ' + str(j - 1) + ']')
    print("S = ", S)
    end = np.argwhere(S == S.max())
    print (S)
    for i in end:
        key = str(list(i))
        value = path[key]
        result = [key]
        traceback(path, S, value, result, seq1, seq2)

def traceback(path, S, value, result, seq1, seq2):
    if value != []:
        key = value[0]
        result.append(key)
        value = path[key]
        i = int((key.split(',')[0]).strip('['))
        j = int((key.split(',')[1]).strip(']'))
    if S[i, j] == 0:
        x = 0
        y = 0
        s1 = ''
        s2 = ''
        md = ''
        for n in range(len(result)-2, -1, -1):
            point = result[n]
            i = int((point.split(',')[0]).strip('['))
            j = int((point.split(',')[1]).strip(']'))
            if i == x:
                s1 += '-'
                s2 += seq2[j-1]
                md += ' '
            elif j == y:
                s1 += seq1[i-1]
                s2 += '-'
                md += ' '
            else:
                s1 += seq1[i-1]
                s2 += seq2[j-1]
                md += '|'
            x = i
            y = j
        print('alignment result:')
        print('s1: %s'%s1)
        print('    '+md)
        print('s2: %s'%s2)
    else:
        traceback(path, S, value, result, seq1, seq2)

In [84]:
Smith_Waterman(sample3, sample4, 1, -1/3, 1)

S =  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 

In [85]:
df2['text'] = df2['text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

NameError: name 'df2' is not defined

In [ ]:
for line 